### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by jameslporter** [JavaPOSWorkingGroup/javapos#1]
New to javaPOS and the website appears to be down no matter which connection I use. Are there example projects or API docs available?

**Comment by jameslporter** [comment]
Site seems to be up now. A getting started guide would be nice for those not familiar, maybe a kitchensink demo app would be nice. For example react navigation has this demo app that shows the commonly used navigation methods. https://expo.io/@react-navigation/NavigationPlayground

**Comment by jameslporter** [comment]
Actually I got confused and was looking at jpos not javapos. Site is not up still.

**Comment by kuniss** [comment]
Please provide the URL you consider to be down.

**Comment by jameslporter** [comment]
The URL in the description of the project: http://javapos.com/

It worked earlier today when I was at home, now at work it's not working. 

dig javapos.com

; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> javapos.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10082
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;javapos.com.                   IN      A

;; ANSWER SECTION:
javapos.com.            6981    IN      A       146.66.66.67

Same answer from @8.8.8.8

http://146.66.66.67/ loads some cleaning service website?

When it did work at my house it seemed to just redirect me to: https://www.omgwiki.org/javapos/ which had practically 0 useful information.

https://downforeveryoneorjustme.com/javapos.com   says down for everyone.

**Comment by jameslporter** [comment]
I think it's some DNS issue with omgwiki.org, seems to load fine now on my corporate internet connection but not on my mobile & laptop on mobile hotspot. At either rate am I missing something or is there really 0 content on this wiki? How do I get started using javaPOS?

**Comment by kuniss** [comment]
@jameslporter 
You are right. I have experienced similar problems with the website from my environments, especially from inside the company firewall.

Unfortunately, the website/domains javapos.com and javapos.org are not anymore under control of the members of the JavaPOS Working Group since the UnifiedPOS (JavaPOS is a platform of) standardization body has been moved from ARTS-NRF to OMG.org. The domains are now under their control. 

The committee body has already asked for letting the domain links point this project's wiki (which is also under construction, however). In June is a regular meeting again. I will bring up the issue there.

**Comment by kuniss** [comment]
How to get started with JavaPOS?
I will try to prepare an introduction to that in the project's wiki in the next weeks. But it depends a little bit on my load at my company...

@jameslporter To give you a short explanation on how to start implementation, I need to know what you want to implement - a JavaPOS application or a JavaPOS device. These are to different provider roles, the JavaPOS control layer is providing an isolation for. 

Nevertheless, a good starting point is to read the architecture overview from the UnifiedPOS specification and the JavaPOS appendix there: https://www.omg.org/cgi-bin/doc?retail/2017-07-32

**Comment by kuniss** [comment]
I will close this issue as it is not directly related to the library implemented herein.
However, feel free to comment further on this issue for communication purposes.
