### ISSUE TITLE
Missing jpos.properties

### ISSUE THREAD

**Issue by mjpcger** [JavaPOSWorkingGroup/javapos#2]
jpos.properties should be present in javapos-1.14.2.jar, retrieved via Maven. Unfortunately, javapos-1.14.2.jar from Maven contains only the following files in jpos/res:

jcl.dtd
jcl.xsd
jcl_profile.dtd

As result, it seems to be impossible to open any JavaPOS device service configured in jpos.xml, only result are three error messages _jpos/res/jpos.properties file not found_ and a JposException.

The workaround is quite easy: Put _jpos.properties_ located in _doc/jpos/res_ of the source distribution of _javapos-config-loader_ into _jpos/res_ of the jar file. However, I think it would be better to have it directly within the jar file from Maven.

**Comment by kuniss** [comment]
The _jpos.properties_ file is the configuration file for the JavaPOS Config Loader (from javapos-config-loader). It MUST NOT be part of any JAR file as it is intended to contain application environment specific configurations regarding which JavaPOS configuration files has to be loaded the JavaPOS Config Loader.

Instead, the jpos.properties file must be put into the subdirectory _jpos/res_ of a Java resource directory which is part of the application's Java classpath. That way, it is ensured it is editable in the file system and a able to be loaded as Java resource by the JavaPOS Config Loader.

As this seems to be a misunderstanding, I'm going to close the issue.

**Comment by putra4648** [comment]
then where should i put `jpos/res/jpos.properties`?
in current project dir or `src/` folder? 
I'm using spring boot

**Comment by kuniss** [comment]
@putra4648, the directory structure `jpos/res/jpos.properties` must be put into a Java resource directory. That directory must be part of your Java classpath.

I guess, you are in your development environment and the Java package directories of your code start in your `src` directory, e.g. `src/com/yourcompany/yourpackage`. If so, the  `jpos/res/jpos.properties` could be placed into that `src` directory and it should get visible for the javapos-config-loader.

However, you should not deploy this in production within your JAR. Instead deploy it in your _config_ directory where your .properties files are located. That _config_ directory you will add to your applications Java classpath for sure.
