### ISSUE TITLE
URLs to non-existent websites

### ISSUE THREAD

**Issue by gskoczylas** [JavaPOSWorkingGroup/javapos#3]
Both in the `readme.md` file and in the _Wiki_ pages there are references either to the www.javapos.com URL or to the www.javapos.org URL. Both URLs are probably wrong. The Internet browser (Chrome) cannot open these pages.

**Comment by kuniss** [comment]
@gskoczylas, they are not wrong, but they are not connected anymore. 

Unfortunately this is out of my control. The domains are now belonging to OMG (omg.org) and I ask the stuff already to forward them at least to the [UnifiedPOS sub page](https://www.omg.org/retail/unified-pos.htm) of OMG. 
This will take some time, I guess. My last request was from December, 23rd 2020...

The old content of javapos.com, however, is gone forever. It has been replaced by this Github project some years ago.
javapos.org had pointed before to javapos.com and later to this Github organization page.

But I will use your issue to get more pressure on OMG. :smile:

**Comment by kuniss** [comment]
OMG has redirected the domains. Both URLS are now poiniting to this Github organization.

I'm going to close this issue.
