### ISSUE TITLE
Possible bug when using escape sequence for "Normal condition": \u001b|N

### ISSUE THREAD

**Issue by boyanlevchev** [JavaPOSWorkingGroup/javapos#8]
Hello, I hope you are well.

At my workplace we use printers that use JPOS drivers. We've got got everything working, but we've come across a peculiar bug.

When printing certain special characters "£" and "€", at first they print out correctly as expected. But if during a receipt print we call the escape sequence `\u001b|N` (The escape command for Restoring printer characteristics to normal condition. Page 244. https://docplayer.net/30157845-Java-for-retail-pos-programming-guide-version-1-2-march-27-international-standard.html), it seems like the code page (or something) also gets reset. 

After using this escape sequence, "£" becomes "ú" and "€" becomes "Ç".

For clarity, we only use this escape sequence as we have a need to bold certain text (using escape sequence `\u001b|bC`), and the only way to un-bold it seems is to use the "restore to normal condition" escape sequence (`\u001b|N`). I have tested and verified that this issue occurs even if I call `\u001b|N` on its own, without bolding beforehand.

Does anybody here have any idea why this is happening, and how we can prevent this?

An example string that is affected:
```
Monetary value: £1.30
\u001b|bCWe bold this text\u001b|N
Another monetary value, that now displays incorrectly: £4.20
```

**Comment by kuniss** [comment]
Hi @boyanlevchev, this is the wrong place for your concern!
You would need to reach out to the JavaPOS device service provider (or the "driver" provider, how you call it, but that's OK :smile:) in case you have the assumption the "driver" does not behave correctly. The implementation provided here by the JavaPOS working group is only a thin layer between the JavaPOS application (your application) and the device service provider's POSPrinter implementation (the "driver") to ensure lose coupling, configuration at runtime and UnifiedPOS compliance.

You may try out the sequence `\u001b|!bC` (note the exclamation mark before _b_). According to the UnifiedPOS standard, this is the sequence to turn off the bold mode. Hopefully, it is implemented right by your device service provider.

... I'm going to close this issue.
